export const genres = [
    'Alternative',
    'Blues',
    'Classical',
    'Country',
    'Dance',
    'Easy Listening',
    'Electronic',
    'Hip Hop / Rap',
    'Indie Pop',
    'Inspirational',
    'K-pop',
    'Jazz',
    'Latin',
    'New Age',
    'Opera',
    'Pop',
    'R&B / Soul',
    'Reggae',
    'Rock',
];